[package]
name = "dock"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
